import {useMemo,useState} from "react";
import type {ReactNode,ChangeEvent} from "react";
import {Icon28ArrowLeftOutline,Icon28ChevronRightOutline} from "@vkontakte/icons";
import {Button,Input,Textarea,Card,Div,Title,Text,Separator} from "@vkontakte/vkui";
import {db,total} from "./store";
import type {Score,Submission} from "./types";
import {criteria} from "./types";

type View="home"|"exhibition"|"join"|"jury"|"results"|"about"|"poster";
const nav:[View,string,string][]=[["home","Главная","⌂"],["exhibition","Выставка","▧"],["join","Участнику","＋"],["jury","Жюри","★"],["results","Результаты","◉"],["about","О конкурсе","i"]];

function Logo(){return <div className="logo"><img className="collegeLogo" src="./college-logo.png" alt="Московский финансовый колледж" /></div>}
function Header({view,setView}:{view:View;setView:(v:View)=>void}){return <header className="topbar"><button className="mobileBack" onClick={()=>setView("home")}><Icon28ArrowLeftOutline/></button><Logo/><nav className="nav">{nav.map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i>{label}</button>)}</nav><button className="lang">EN</button></header>}
function Hero({setView}:{setView:(v:View)=>void}){return <section className="hero"><div className="heroCopy"><div className="eyebrow">WORLD SAVINGS DAY · OCTOBER 31</div><h1>SAVE <em>THE FUTURE</em></h1><div className="sub">AI DIGITAL POSTER CHALLENGE</div><p>Smart choices today. A more secure tomorrow.</p><div className="pillrow"><span>FINANCIAL LITERACY</span><span>INNOVATION WITH AI</span><span>BRIGHTER OPPORTUNITIES</span></div></div><div className="heroArt"><div className="chart"><span>+24%</span><div className="bars"><i/><i/><i/><i/><i/></div></div><div className="coin c1">₽</div><div className="coin c2">$</div><div className="pig">◒</div></div><div className="heroActions"><Button mode="primary" size="l" onClick={()=>setView("exhibition")}>Смотреть работы <Icon28ChevronRightOutline/></Button><Button mode="secondary" size="l" onClick={()=>setView("join")}>Подать работу</Button></div></section>}
function Home({setView}:{setView:(v:View)=>void}){return <><Hero setView={setView}/><div className="featureGrid">{[["ВЫСТАВКА","СМОТРЕТЬ РАБОТЫ","▧","exhibition"],["УЧАСТНИКУ","ПОДАТЬ РАБОТУ","＋","join"],["ЖЮРИ","ОЦЕНИВАТЬ РАБОТЫ","★","jury"],["РЕЗУЛЬТАТЫ","ИТОГИ КОНКУРСА","◉","results"],["О КОНКУРСЕ","ЦЕЛИ И НОМИНАЦИИ","i","about"]].map(([a,b,c,v])=><button className="feature" key={v} onClick={()=>setView(v as View)}><span>{c}</span><b>{a}</b><small>{b}</small></button>)}</div><footer>Московский финансовый колледж · © 2026 SAVE THE FUTURE | VSproduction</footer></>}
function Page({title,lead,children}:{title:string;lead?:string;children?:ReactNode}){return <main className="page"><div className="pageHead"><Title level="1">{title}</Title>{lead&&<Text className="lead">{lead}</Text>}</div>{children}</main>}
function PosterCard({w,onClick}:{w:Submission;onClick:()=>void}){return <Card className="posterCard" onClick={onClick}><div className="posterVisual">{w.imageUrl?<img src={w.imageUrl}/>:<><span className="posterNo">#{w.posterNo}</span><strong>{w.title}</strong><small>{w.idea}</small></>}</div><Div><Text weight="2">#{w.posterNo} · {w.interactive?"INTERACTIVE":"DIGITAL POSTER"}</Text><Text className="muted">«Этот постер заставил меня задуматься» · {w.audience}</Text></Div></Card>}
function Exhibition({setView}:{setView:(v:View)=>void}){const works=db.submissions().filter(x=>x.status==="published"||x.status==="winner");return <Page title="Цифровая выставка" lead="Работы участников. Авторы скрыты на этапе оценки."><div className="filters"><Button mode="secondary">Все</Button><Button mode="secondary">AI poster</Button><Button mode="secondary">Interactive</Button></div><div className="posterGrid">{works.map(w=><PosterCard key={w.id} w={w} onClick={()=>{sessionStorage.setItem("poster",w.id);setView("poster")}}/>)}</div></Page>}
function Join(){const [f,setF]=useState({title:"",idea:"",problem:"",author:"",group:"",contact:"",tools:"",aiHow:"",contribution:"",interactiveUrl:""});const [done,setDone]=useState(false);const u=(k:keyof typeof f)=>(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setF({...f,[k]:e.target.value});const submit=()=>{if(!f.title||!f.idea||!f.aiHow)return;db.add({id:crypto.randomUUID(),posterNo:Math.floor(100+Math.random()*900),...f,interactive:!!f.interactiveUrl,status:"moderation",createdAt:new Date().toISOString(),audience:0});setDone(true)};return <Page title="Подать работу" lead="Один конкурсный постер. Одна сильная идея. Один главный посыл."><Card className="formCard"><Input value={f.author} onChange={u("author")} placeholder="Имя и фамилия"/><Input value={f.group} onChange={u("group")} placeholder="Группа / курс"/><Input value={f.contact} onChange={u("contact")} placeholder="Контакт"/><Input value={f.title} onChange={u("title")} placeholder="Poster title · English"/><Textarea value={f.problem} onChange={u("problem")} placeholder="Какую проблему, связанную со сбережениями, вы хотите поднять?"/><Textarea value={f.idea} onChange={u("idea")} placeholder="Главная идея / message"/><Text className="hint">На постере: английский заголовок, короткое сообщение, визуальная концепция, призыв к действию или вопрос. Рекомендуемый объём основного текста — до 35 слов.</Text><Input value={f.tools} onChange={u("tools")} placeholder="Какие AI-инструменты использовали?"/><Textarea value={f.aiHow} onChange={u("aiHow")} placeholder="Генерация идей, английский текст, изображение, редактирование, композиция..."/><Textarea value={f.contribution} onChange={u("contribution")} placeholder="Что сделали самостоятельно?"/><Input value={f.interactiveUrl} onChange={u("interactiveUrl")} placeholder="Ссылка на интерактивный элемент · optional"/><Button stretched size="l" mode="primary" onClick={submit}>Отправить на модерацию</Button>{done&&<div className="success">Работа отправлена. Статус: SUBMITTED → ожидает модерации.</div>}</Card></Page>}
function Jury(){const works=db.submissions().filter(x=>x.status==="published"||x.status==="winner");const [selected,setSelected]=useState("");const [score,setScore]=useState<Score>({idea:10,english:10,originality:10,design:10,digital:10});return <Page title="Жюри" lead="Анонимная оценка опубликованных работ. Каждый критерий — 0–20 баллов."><div className="juryGrid"><div>{works.map(w=><button className={selected===w.id?"juryRow selected":"juryRow"} onClick={()=>setSelected(w.id)} key={w.id}><b>#{w.posterNo}</b><span>{w.title}</span></button>)}</div><Card className="scoreCard">{selected?<><Title level="3">Постер #{works.find(w=>w.id===selected)?.posterNo}</Title>{criteria.map(([key,label])=><div className="scoreLine" key={key}><span>{label}</span><input type="range" min="0" max="20" value={score[key]} onChange={e=>setScore({...score,[key]:+e.target.value})}/><b>{score[key]}</b></div>)}<Separator/><Title level="2">{total(score)} / 100</Title><Button stretched mode="primary" onClick={()=>db.score(selected,score)}>Сохранить оценку</Button></>:<Text>Выберите работу.</Text>}</Card></div></Page>}
function Results(){const works=db.submissions().filter(x=>x.status==="published"||x.status==="winner");const scores=db.scores();return <Page title="Результаты" lead="Итоги конкурса и отдельная реакция аудитории."><div className="resultList">{works.map(w=><Card key={w.id}><div className="resultRow"><b>#{w.posterNo}</b><span>{w.title}</span><strong>{total(scores[w.id])||"—"} / 100</strong></div></Card>)}</div></Page>}
function About(){return <Page title="О конкурсе" lead="SAVE THE FUTURE объединяет финансовую грамотность, английский язык, AI и цифровой дизайн."><div className="aboutGrid">{[["Задача","Не сделать красивый постер о сбережениях, а создать постер, который заставляет задуматься о конкретной финансовой проблеме и действии."],["Номинации","GRAND PRIX · BEST COMMUNICATION IDEA · BEST ENGLISH POSTER · BEST DIGITAL DESIGN · BEST INTERACTIVE POSTER · отдельный AUDIENCE CHOICE."],["Правила","AI разрешён и является частью конкурса. Автор заполняет короткий AI Creative Passport. Реакция аудитории не влияет на оценку жюри."],["5 критериев","Communication idea · English language · Originality of concept · Visual design · Meaningful use of AI & digital technologies."]].map(([h,t])=><Card key={h}><Title level="2">{h}</Title><Text>{t}</Text></Card>)}</div></Page>}
function Poster({setView}:{setView:(v:View)=>void}){const w=db.submissions().find(x=>x.id===sessionStorage.getItem("poster"));if(!w)return <Page title="Работа не найдена"><Button onClick={()=>setView("exhibition")}>К выставке</Button></Page>;return <Page title={"Постер #"+w.posterNo} lead={w.title}><Card className="detailCard"><div className="posterDetail">{w.imageUrl?<img src={w.imageUrl}/>:<div className="posterVisual big"><strong>{w.title}</strong><small>{w.idea}</small></div>}</div><Title level="3">AI Creative Passport</Title><Text><b>Инструменты:</b> {w.tools||"—"}</Text><Text><b>Как использовали AI:</b> {w.aiHow||"—"}</Text><Text><b>Что сделали самостоятельно:</b> {w.contribution||"—"}</Text><Button mode="secondary" onClick={()=>setView("exhibition")}>← Назад к выставке</Button></Card></Page>}
export default function App(){const [view,setView]=useState<View>("home");const body=useMemo(()=>{switch(view){case"home":return <Home setView={setView}/>;case"exhibition":return <Exhibition setView={setView}/>;case"join":return <Join/>;case"jury":return <Jury/>;case"results":return <Results/>;case"about":return <About/>;case"poster":return <Poster setView={setView}/>}},[view]);return <div className="app"><Header view={view} setView={setView}/>{body}</div>}